### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@lwrjs/config' imported

### ISSUE THREAD

**Issue by lukethacoder** [lukethacoder/lwc-module-resolver#2]
@rahulgawale have moved your issue here as it looks like you're not using LWC Garden specifically, but `lwr dev` more generally.

> 
> I have installed the `@lukethacoder/lwrjs-module-registry` package.
> 
> this is the snippet from the `package.json` file.
> ```
>   "overrides": {
>     "@lwc/module-resolver": "$@lukethacoder/lwc-module-resolver"
>   }
> ```
> 
> Following is `lwr.config.js`.
> 
> ```
> {
> 	"lwc": {
> 		"modules": [
> 			{
> 				"dir": "/src/modules/app",
> 				"namespace": "app"
> 			},
> 			{
> 				"dir": "/src/modules/ui",
> 				"namespace": "ui"
> 			},
> 			{
> 				"name": "contexts",
> 				"path": "/src/contexts/contexts.js"
> 			}
> 		]
> 	},
> 	"routes": [
> 		{
> 			"id": "app",
> 			"path": "/",
> 			"rootComponent": "app/root",
> 			"layoutTemplate": "$layoutsDir/app.html",
> 			"bootstrap": {
> 				"syntheticShadow": true
> 			}
> 		},
> 		{
> 			"id": "auth-callback",
> 			"path": "/auth-callback",
> 			"rootComponent": "ui/card",
> 			"layoutTemplate": "$layoutsDir/auth-callback.html"
> 		}
> 	],
> 	"bundleConfig": {
> 		"exclude": [
> 			"lwc"
> 		]
> 	},
> 	"assets": [
> 		{
> 			"alias": "jsforceDir",
> 			"dir": "$rootDir/src/jsforce",
> 			"urlPath": "/jsforce"
> 		},
> 		{
> 			"dir": "$rootDir/src/assets/fonts",
> 			"urlPath": "/fonts"
> 		},
> 		{
> 			"file": "$rootDir/src/assets/utilitySprite.svg",
> 			"urlPath": "/lightning.utilitySprite"
> 		},
> 		{
> 			"alias": "assetsDir",
> 			"dir": "$rootDir/src/assets",
> 			"urlPath": "/assets"
> 		}
> 	]
> }
> ```
> 
> When I ran `npm run dev` it gave me this error on windows.
> 
> ```
> PS D:\KTL Projects\crudspace> npm run dev
> 
> > crudspace@0.0.1 dev
> > lwr dev
> 
> node:internal/modules/esm/resolve:853
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
>         ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@lwrjs/config' imported from D:\KTL Projects\crudspace\node_modules\@lwrjs\module-registry\build\es\signature.js
>     at packageResolve (node:internal/modules/esm/resolve:853:9)
>     at moduleResolve (node:internal/modules/esm/resolve:910:20)
>     at defaultResolve (node:internal/modules/esm/resolve:1130:11)
>     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
>     at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
>     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
>     at link (node:internal/modules/esm/module_job:84:36) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
> 
> Node.js v20.11.0
> ```
> Am I missing anything?

_Originally posted by @rahulgawale in https://github.com/lukethacoder/lwc-garden/issues/3#issuecomment-2071671021_

**Comment by lukethacoder** [comment]
@rahulgawale

Looks like the error is flagging it can't find the `@lwrjs/config` package. Try installing that.

If you're still having issues, the package only supports ESM (for now), so if you're attempting to use within a CJS environment, things probably won't work as nicely (or at all).

**Comment by rahulgawale** [comment]
@lukethacoder you are right I am using lwr and not lwc garden.

I installed it and it started working, but I am not sure if your custom module resolver is working or not. Because change in lwr.config.json does not affect the app. I will test it further and get back to you if there are any issues.

**Comment by lukethacoder** [comment]
@rahulgawale

https://stackblitz.com/edit/lukethacoder-lwc-module-resolver?file=components%2Fapp%2Fapp.html

Whipped up a quick example repo if you're curious. Can see the multi `dirs` config is working as both the `c-hello-world` and `c-button` are being resolved correctly even though they are in different folders. If this was using the standard resolver, this would throw errors about invalid config.

Looking at your config, you're using the `namespace` value, which is not part of the standard `@lwc/module-resolver` config. So if your LWCs are rendering (e.g. `<ui-button></ui-button`, `<app-main></app-main>`) it will be using the custom resolver.

If you are still having issues, an example repo would be handy to properly diagnose the issue.

**Comment by rahulgawale** [comment]
@lukethacoder thanks I will give it a try and get back to you.
